apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: examples.my.domain
spec:
  scope: Namespaced
  names:
    kind: Example
    plural: examples
  group: my.domain
  versions:
    - name: v1alpha1
      storage: true
      served: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                property1:
                  type: string
                property2:
                  type: number
                  format: int32
      additionalPrinterColumns:
        - name: PropertyOne
          type: string
          jsonPath: .spec.property1
        - name: PropertyTwo
          type: string
          jsonPath: .spec.property2
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
