{
 "title": "Slinky / Slurm",
 "tags": [
  "slinky",
  "slurm"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Nodes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "slurm_node_total", "legendFormat": "Total" },
    { "expr": "slurm_alloc_nodes", "legendFormat": "Allocated" },
    { "expr": "slurm_idle_nodes", "legendFormat": "Idle" },
    { "expr": "slurm_mixed_nodes", "legendFormat": "Mixed" }
   ]
  },
  {
   "title": "Partition CPU Allocation",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slurm_partition_alloc_cpus\n/\nslurm_partition_cpus",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "Partition Nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "slurm_partition_nodes", "legendFormat": "{{partition}}" }
   ]
  },
  {
   "title": "Jobs",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "slurm_partition_jobs", "legendFormat": "Total ({{partition}})" },
    { "expr": "slurm_partition_pending_jobs", "legendFormat": "Pending ({{partition}})" },
    { "expr": "slurm_partition_running_jobs", "legendFormat": "Running ({{partition}})" }
   ]
  }
 ]
}