{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.exporter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "slurm-exporter.name" . }}
  namespace: {{ include "slurm-exporter.namespace" . }}
  labels:
    {{- include "slurm-exporter.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "slurm-exporter.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      protocol: TCP
      port: {{ include "slurm-exporter.port" . }}
      targetPort: {{ include "slurm-exporter.port" . }}
{{- end }}{{- /* if .Values.exporter.enabled */}}
