{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if and (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") .Values.exporter.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "slurm-exporter.name" . }}
  namespace: {{ include "slurm-exporter.namespace" . }}
  labels:
    {{- include "slurm-exporter.labels" . | nindent 4 }}
spec:
  endpoints:
  - interval: 5s
    port: metrics
    scheme: http
  namespaceSelector:
    matchNames:
    - {{ include "slurm-exporter.namespace" . }}
  selector:
    matchLabels:
      {{- include "slurm-exporter.selectorLabels" . | nindent 6 }}
{{- end }}{{- /* if and (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") .Values.exporter.serviceMonitor.enabled */}}
