apiVersion: v1
kind: Secret
metadata:
  name: test-secret
type: Opaque
data:
  # The value is base64 encoded "abc".
  # NOTE that it's an error when using the value as value of an environment variable
  # if the decoded value contains null char (\0). In that case, the container using
  # the secrete won't start.
  key1: YWJj
stringData:
  key2: abc2
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    name: test-pod
spec:
  containers:
  - name: test-pod
    image: registry.k8s.io/busybox:1.27.2
    command: [ "/bin/sh", "-c", "env" ]
    # NOTE that each env var can be from a different Secret than others.
    env:
    - name: ENV_KEY1
      valueFrom:
        secretKeyRef:
          name: test-secret
          key: key1
    - name: ENV_KEY2
      valueFrom:
        secretKeyRef:
          name: test-secret
          key: key2
  restartPolicy: Never
