apiVersion: v1
kind: Secret
metadata:
  name: test-secret
type: Opaque
data:
  # The value is base64 encoded "abc".
  key1: YWJj
stringData:
  key2: abc2
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    name: test-pod
spec:
  containers:
  - name: test-pod
    image: registry.k8s.io/busybox:1.27.2
    command: [ "/bin/sh", "-c", "cd /etc/config && ls -l && for f in *; do echo $f && cat $f; done" ]
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/config
  volumes:
  - name: secret-volume
    secret:
      secretName: test-secret
      items:
      - key: key1
        path: secretfile1
      - key: key2
        path: secretfile2
  restartPolicy: Never
