apiVersion: apps/v1
kind: Deployment
metadata:
  name: v2-hello-{{ .Release.Name }}-{{ .Release.Revision }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx:1.29.0
        ports:
        - containerPort: 80
