apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  schedulerName: custom-scheduler
  containers:
    - name: main
      image: busybox
      command: ["sleep", "3600"]
      resources:
        limits:
          example.com/foo: 1
