apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  namespace: kube-system
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    extenders:
    - urlPrefix: http://host.docker.internal:5116/api/v1/extender
      filterVerb: filter
      nodeCacheCapable: false
      managedResources:
      - name: example.com/foo
        ignoredByScheduler: true
